//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_bill> tbl_bill { get; set; }
        public virtual DbSet<tbl_cargo> tbl_cargo { get; set; }
        public virtual DbSet<tbl_CargoInf> tbl_CargoInf { get; set; }
        public virtual DbSet<tbl_crw> tbl_crw { get; set; }
        public virtual DbSet<tbl_crwInf> tbl_crwInf { get; set; }
        public virtual DbSet<tbl_deliverygrid> tbl_deliverygrid { get; set; }
        public virtual DbSet<tbl_deliveryinfo> tbl_deliveryinfo { get; set; }
        public virtual DbSet<tbl_ImoGen> tbl_ImoGen { get; set; }
        public virtual DbSet<tbl_InvInfo> tbl_InvInfo { get; set; }
        public virtual DbSet<tbl_invoice> tbl_invoice { get; set; }
        public virtual DbSet<tbl_manifest> tbl_manifest { get; set; }
        public virtual DbSet<tbl_ManifestInfo> tbl_ManifestInfo { get; set; }
    }
}
