//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ManifestInfo
    {
        public int Id { get; set; }
        public string maniMaster { get; set; }
        public string fromPortMani { get; set; }
        public string portofMani { get; set; }
        public string DateMani { get; set; }
        public string voyage_mani { get; set; }
        public string general_mani { get; set; }
    }
}
