//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ImoGen
    {
        public int Id { get; set; }
        public string nameship { get; set; }
        public string ArrDepa { get; set; }
        public string flag { get; set; }
        public string imo_num { get; set; }
        public string callsign { get; set; }
        public string master_name { get; set; }
        public string agent_ship { get; set; }
        public string portA { get; set; }
        public string portdes { get; set; }
        public string dateAD { get; set; }
        public string brifeVoy { get; set; }
        public string arrivedDes { get; set; }
        public string position_ship { get; set; }
        public string passenger_number { get; set; }
        public string crew_number { get; set; }
        public string gross_ton { get; set; }
        public string net_ton { get; set; }
        public string brife_cargo { get; set; }
        public string registry { get; set; }
        public string remarks { get; set; }
        public string attached_doc { get; set; }
        public string ship_dec { get; set; }
        public string passenger_list { get; set; }
        public string cargo_dec { get; set; }
        public string crew_list { get; set; }
        public string crew_effect { get; set; }
        public string maritime_dec { get; set; }
        public string ships_req { get; set; }
        public string voyage_num { get; set; }
    }
}
