//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_manifest
    {
        public int Id { get; set; }
        public string BL_no { get; set; }
        public Nullable<double> weight { get; set; }
        public string weight_unit { get; set; }
        public string mark_remark { get; set; }
        public string consignee { get; set; }
        public string shipper { get; set; }
        public string description { get; set; }
    }
}
