//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bill
    {
        public int Id { get; set; }
        public string bl_num { get; set; }
        public string shipper_name { get; set; }
        public string shipper_tel { get; set; }
        public string shipper_adr { get; set; }
        public string consignee_name_ { get; set; }
        public string consignee_tel { get; set; }
        public string notify_adr { get; set; }
        public string vessel { get; set; }
        public string voyage_num { get; set; }
        public string port_del { get; set; }
        public string port_load { get; set; }
        public string port_dis { get; set; }
        public string shipper_good { get; set; }
        public string gross { get; set; }
        public string time_used { get; set; }
        public string place_issue { get; set; }
        public string name_agent_dis { get; set; }
        public string agent_dis_add { get; set; }
        public string phone_tel { get; set; }
        public string cpt { get; set; }
    }
}
