//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CargoInf
    {
        public int Id { get; set; }
        public string call_sign { get; set; }
        public string name_ship { get; set; }
        public Nullable<int> imo_number { get; set; }
        public string port_report { get; set; }
        public string flag_ship { get; set; }
        public string masters_name { get; set; }
        public string portOfLoading { get; set; }
        public string portOfDischarge { get; set; }
        public string ArrivalDeparture { get; set; }
    }
}
