//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_crwInf
    {
        public int Id { get; set; }
        public string call_signcrw { get; set; }
        public string name_shipcrw { get; set; }
        public string voyage_crw { get; set; }
        public string port_arr_dep { get; set; }
        public string flag_crw { get; set; }
        public string imo_crw { get; set; }
        public string lastReportCall_crw { get; set; }
        public string date_arr_depar { get; set; }
        public string crw_arr_depar { get; set; }
    }
}
