//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_deliveryinfo
    {
        public int Id { get; set; }
        public string date { get; set; }
        public string BL_no { get; set; }
        public string director { get; set; }
        public string final_destination { get; set; }
        public string vessel { get; set; }
        public string voyage { get; set; }
        public string good_des { get; set; }
        public string gross_unit { get; set; }
        public string delivery_exp { get; set; }
    }
}
