//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_crw
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string ranking { get; set; }
        public string nationality { get; set; }
        public string cdc_num { get; set; }
        public string cdc_exp { get; set; }
        public string passport_num { get; set; }
        public string passport_exp { get; set; }
        public string date_birth { get; set; }
        public string birthplace { get; set; }
    }
}
