//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvInfo
    {
        public int Id { get; set; }
        public string delivery { get; set; }
        public string vessel { get; set; }
        public Nullable<int> voyage { get; set; }
        public string invoice_no { get; set; }
        public string date_inv { get; set; }
    }
}
