//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PishgamanFormsAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cargo
    {
        public int Id { get; set; }
        public string alaem_va_shomareha { get; set; }
        public string kala_girande { get; set; }
        public string andaze { get; set; }
        public string noe_baste { get; set; }
        public Nullable<double> vazn_nakhales { get; set; }
        public Nullable<int> tedad { get; set; }
        public string vazn_unit { get; set; }
        public string sharh_kala { get; set; }
    }
}
